version: '3'

services:
    php:
        container_name: event-wave-api
        build:
            context: ./docker/php
        environment:
            PHP_IDE_CONFIG: "serverName=event-wave"
            XDEBUG_MODE: ${XDEBUG_MODE}
            XDEBUG_CONFIG: ${XDEBUG_CONFIG}
        ports:
            - '9000:9000'
        volumes:
            - ./:/var/www/event-wave
    nginx:
        container_name: event-wave-nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/event-wave
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    mysql:
        container_name: event-wave-db
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        ports:
            - "${DB_PORT}:3306"
        expose:
            - "${DB_PORT}"
        volumes:
            - ./mysql:/var/lib/mysql/
    mysql-testing:
        container_name: event-wave-db-testing
        image: mysql:5.7
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        ports:
            - "3366:3306"
        expose:
            - 3366
        volumes:
            - ./mysql-testing:/var/lib/mysql/
